name: Backend Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build \
          -t student-management-api .

      - name: Tag and Push Docker Image
        env:
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
        run: |
          if [ -z "$ECR_REPOSITORY" ]; then
            echo "Error: ECR_REPOSITORY secret is not configured in GitHub Secrets!"
            exit 1
          fi
          docker tag student-management-api:latest $ECR_REPOSITORY:latest
          docker push $ECR_REPOSITORY:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |

            aws ecr get-login-password \
            --region us-east-1 | docker login \
            --username AWS \
            --password-stdin \
            ${{ secrets.ECR_REGISTRY }}

            docker pull \
            ${{ secrets.ECR_REPOSITORY }}:latest

            docker stop student-api || true

            docker rm student-api || true

            docker run -d \
            --name student-api \
            --restart always \
            -p 8080:8080 \
            ${{ secrets.ECR_REPOSITORY }}:latest