name: Frontend Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build \
          --build-arg VITE_API_URL=${{ secrets.VITE_API_URL || 'http://localhost:8080' }} \
          -t student-management-ui .

      - name: Tag and Push Docker Image
        env:
          FRONTEND_ECR_REPOSITORY: ${{ secrets.FRONTEND_ECR_REPOSITORY }}
        run: |
          if [ -z "$FRONTEND_ECR_REPOSITORY" ]; then
            echo "Error: FRONTEND_ECR_REPOSITORY secret is not configured in GitHub Secrets!"
            exit 1
          fi
          docker tag student-management-ui:latest $FRONTEND_ECR_REPOSITORY:frontend-latest
          docker push $FRONTEND_ECR_REPOSITORY:frontend-latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |

            aws ecr get-login-password \
            --region us-east-1 | docker login \
            --username AWS \
            --password-stdin ${{ secrets.ECR_REGISTRY}}

            docker pull ${{ secrets.FRONTEND_ECR_REPOSITORY }}:frontend-latest

            docker stop student-ui || true

            docker rm student-ui || true

            docker run -d \
            --name student-ui \
            --restart always \
            -p 80:80 \
            ${{ secrets.FRONTEND_ECR_REPOSITORY }}:frontend-latest